config/routes.rb
Rails.application.routes.draw do

  resources :client
  resources :client_stock
  resources :stock

end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :client_stocks
  has_many :stocks, through: :client_stocks
end

app/models/client_stock.rb
class ClientStock < ActiveRecord::Base
  belongs_to :client
  belongs_to :stock
end

app/models/stock.rb
class Stock < ActiveRecord::Base
  has_many :client_stocks
  has_many :clients, through: :client_stocks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/client_controller.rb
class ClientController < ApplicationController


  def index
    @title = 'Clients'
    @clients = Client.all
  end


  def show
    @title = 'View Client'
    @client = Client.find(params[:id])

  end

  def new
    @client = Client.new
    render :new
  end

  def create
    client = Client.new(client_params)
    
    if client.save
      redirect_to '/client'
    else
      render :new
    end
  end

  def edit
    @client = Client.find(params[:id])
  end

  def update
    client = Client.find(params[:id])

    if client.update(client_params)
      redirect_to client_path
    else
      render :edit
    end
  end

  def destroy
    client = Client.find(params[:id]).destroy

    redirect_to '/client'
  end

  private
  def client_params
    params.require(:client).permit(:name, :balance)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/client_helper.rb
module ClientHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/client/edit.html.erb
<%= form_for @client do |form| %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="field">
    <%= form.label :balance %>
    <%= form.text_field :balance %>
  </div>
  <div class="action">
    <%= form.submit 'Update' %>
  </div>

<% end %>

app/views/client/index.html.erb
<%= link_to 'Register Client', new_client_path %>

<div id='clients'>
<% @clients.each do |client| %>

  <div class='client-show'>
    <h2>Client ID: #<%= client.id %></h2>

    <p>Name: <%= link_to client.name, client %></p>
    <p>Current Blance: <%= client.balance %></p>

  </div>
<% end %>
</div>

app/views/client/new.html.erb
<%= form_for @client, :url => { :action => "create" } do |form| %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="field">
    <%= form.label :balance %>
    <%= form.text_field :balance %>
  </div>
  <div class="action">
    <%= form.submit 'Register' %>
  </div>

<% end %>

app/views/client/show.html.erb
<h2>Client ID: #<%= @client.id %></h2>

  <div class='showClient'>

    <p>Name: <%= @client.name %></p>
    <p>Current Balance: <%= @client.balance %></p>
    <%= link_to 'Delete Client', @client, method: :delete, data: { confirm: "Are you sure?" } %>
    <%= link_to 'Edit Client', edit_client_path(@client) %><br>
    <%= link_to '<< Back to Clients', client_index_path %>


  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BankingApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>